name: Accept New Golden Image

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  accept-image:
    uses: mpiispanen/image-comparison-and-update/.github/workflows/accept-image.yml@main
    permissions:
      contents: write
      issues: write
      pull-requests: write